Fix linking of src/canvas_glx.o
Otherwise:
/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.4/../../../../x86_64-pc-linux-gnu/bin/ld: canvas_glx.o: undefined reference to symbol 'XPending'
/usr/lib64/libX11.so.6: error adding symbols: DSO missing from command line